#ifndef HELPZ_NET_DEFS_H
#define HELPZ_NET_DEFS_H

#define HELPZ_MAX_UDP_PACKET_SIZE 65507

#define HELPZ_MAX_PACKET_DATA_SIZE (HELPZ_MAX_UDP_PACKET_SIZE - 17)
#define HELPZ_MAX_MESSAGE_DATA_SIZE (HELPZ_MAX_PACKET_DATA_SIZE / 2)

#define HELPZ_PROTOCOL_MAX_MESSAGE_SIZE 2147483648

#endif // HELPZ_NET_DEFS_H
