#ifndef HELPZ_NET_DEFS_H
#define HELPZ_NET_DEFS_H

#define MAX_UDP_PACKET_SIZE 65507

#define MAX_PACKET_DATA_SIZE (MAX_UDP_PACKET_SIZE - 17)
#define MAX_MESSAGE_DATA_SIZE (MAX_PACKET_DATA_SIZE / 2)

#endif // HELPZ_NET_DEFS_H
