set(PROJECT_VERSION_MAJOR 1)
set(PROJECT_VERSION_MINOR 3)
set(PROJECT_VERSION_BUILD 100)

set(CMAKE_PROJECT_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CMAKE_PROJECT_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CMAKE_PROJECT_VERSION_PATCH ${PROJECT_VERSION_PATCH})
